### ISSUE TITLE
ランダム選出

### ISSUE THREAD

**Issue by c0b21055** [c0b21009/ProExD#4]
https://github.com/c0b21009/ProExD/blob/98adf1956ca47db89c9d1c292904a5a953bf7018/ex01/alphabet.py#L11

アルファベットを26文字打つのではなく、選出すればもっとプログラミングが見やすくなると思う。

**Comment by c0b21009** [comment]
unicodeを用いて短い文に書き換えました。ご指摘ありがとうございました。
