### ISSUE TITLE
コード内容の説明

### ISSUE THREAD

**Issue by pipopixu** [c0b21009/ProExD#8]
https://github.com/c0b21009/ProExD/blob/6da1799a42c68d8365370650a098b61b3ac399b9/ex03/maze.py#L88

コードの内容を簡単にコメントアウトで記載するとより良くなると思います。

**Comment by c0b21009** [comment]
https://github.com/c0b21009/ProExD/commit/37bab77030969e16e8b705443179171957eaf849

commit "final #7"で修正しました。コメントありがとうございました!!
